name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5' # Replace with your Flutter version if different

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy Preview to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_874C2 }}
          projectId: portfolio-874c2